//
//  ExecutionPlan.swift
//  codellama
//
//  Created by Thiago Duarte on 3/14/26.
//

import Foundation

/// A structured plan of tool-calling steps generated by the agent.
///
/// Plans start in `.draft` status and transition through approval and
/// execution before reaching a terminal state (`.completed` or `.failed`).
struct ExecutionPlan: Codable, Identifiable, Sendable {
    let id: UUID
    var intent: String
    var contextSummary: String
    var steps: [AgentStep]
    var status: PlanStatus

    /// The lifecycle status of an execution plan.
    enum PlanStatus: String, Codable, Sendable {
        case draft
        case awaitingApproval
        case executing
        case completed
        case failed
        case cancelled
    }

    init(
        id: UUID = UUID(),
        intent: String,
        contextSummary: String,
        steps: [AgentStep],
        status: PlanStatus = .draft
    ) {
        self.id = id
        self.intent = intent
        self.contextSummary = contextSummary
        self.steps = steps
        self.status = status
    }
}

// MARK: - AgentStep

/// A single step within an `ExecutionPlan`, wrapping a `ToolCall` with
/// execution metadata (status, result, timing).
struct AgentStep: Codable, Identifiable, Sendable {
    let id: UUID
    let index: Int
    let description: String
    let toolCall: ToolCall
    var status: StepStatus
    var result: ToolResult?
    var startedAt: Date?
    var completedAt: Date?

    /// The execution status of an individual agent step.
    enum StepStatus: String, Codable, Sendable {
        case pending
        case running
        case succeeded
        case failed
        case skipped
    }

    init(
        id: UUID = UUID(),
        index: Int,
        description: String,
        toolCall: ToolCall,
        status: StepStatus = .pending,
        result: ToolResult? = nil,
        startedAt: Date? = nil,
        completedAt: Date? = nil
    ) {
        self.id = id
        self.index = index
        self.description = description
        self.toolCall = toolCall
        self.status = status
        self.result = result
        self.startedAt = startedAt
        self.completedAt = completedAt
    }
}
